POST https://shark-app-m2z8h.ondigitalocean.app/login
Content-Type: application/json

{"username": "Millie", "password": "ilovesenka"}

###

POST https://shark-app-m2z8h.ondigitalocean.app/signup
Content-Type: application/json

{"username": "Test", "password": "ilovesenka", "email": "olliebechstein@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 42e2779c469a7abb1904b7b39f011b70092196ea

{}

###

POST http://127.0.0.1:8000/api/planes/capture/
Content-Type: application/json
Authorization: Token 42e2779c469a7abb1904b7b39f011b70092196ea

{"lat": "51.384880", "lon": "-2.361970"}


###


GET http://127.0.0.1:8000/api/planes/
Content-Type: application/json
Authorization: Token 42e2779c469a7abb1904b7b39f011b70092196ea

###

DELETE http://127.0.0.1:8000/api/planes/delete/
Content-Type: application/json
Authorization: Token 42e2779c469a7abb1904b7b39f011b70092196ea

{"id": "1"}