POST https://shark-app-m2z8h.ondigitalocean.app/login
Content-Type: application/json

{"username": "Millie", "password": "ilovesenka"}

###

POST https://shark-app-m2z8h.ondigitalocean.app/signup
Content-Type: application/json

{"username": "Billy2", "password": "ilovesenka", "email": "olliebechstein@gmail.com"}

###

GET https://shark-app-m2z8h.ondigitalocean.app/test_token
Content-Type: application/json
Authorization: Token 8a8ae2640ad7d5396a7232766edec5c7fb185a83

{}

###

POST http://127.0.0.1:8000/api/planes/capture/
Content-Type: application/json
Authorization: Token 42e2779c469a7abb1904b7b39f011b70092196ea

{"lat": "43.896576", "lon": "22.280081"}


###


GET https://shark-app-m2z8h.ondigitalocean.app/api/planes/
Content-Type: application/json
Authorization: Token 42e2779c469a7abb1904b7b39f011b70092196ea
###

DELETE https://shark-app-m2z8h.ondigitalocean.app/api/planes/delete/
Content-Type: application/json
Authorization: Token 42e2779c469a7abb1904b7b39f011b70092196ea

{"id": "22"}

###

GET https://api.planespotters.net/pub/photos/reg/G-SUNF


###


GET https://shark-app-m2z8h.ondigitalocean.app/api/planes/top
Content-Type: application/json
Authorization: Token 42e2779c469a7abb1904b7b39f011b70092196ea

{}
