POST https://shark-app-m2z8h.ondigitalocean.app/login
Content-Type: application/json

{"username": "Ollie1234", "password": "ilovesenka"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "Olliea3", "password": "ilovesenka", "email": "olliebechstein@gmail.com"}

###

GET https://shark-app-m2z8h.ondigitalocean.app/test_token
Content-Type: application/json
Authorization: Token 05c3f7aea9b5165a6951de00221bab00029199cc

{}

###

POST http://127.0.0.1:8000/planes/
Content-Type: application/json
Authorization: Token 05c3f7aea9b5165a6951de00221bab00029199cc

{"type": "A320", "reg": "G-TEST"}
